### ISSUE TITLE
  `/user` command to show details of user

### ISSUE THREAD

**Issue by j24m** [Real-Dev-Squad/discord-slash-commands#106]
## Description
- The `/user` command will take one argument, which is the username of the user whose details you want to see.
- The command will then search the system for a user with that username.
- If the user is found, the command will display the following information about the user :
-> Full name
-> Date Joined
-> Status (Idle, active, ooo, onboarding) 
-> If the user is not found, the command will not display any output.
- **Here is an example of how to use the /user command**:
$ /user testuser
Full name : test user
Date Joined : Wed Aug 10 12:34:56 2023
Status : (Active, OOO, Idle, Onboarding)

## Acceptance Criteria
- The command must accept one argument, which is the username of the user whose details you want to see.
- The command must search the system for a user with that username.
- If the user is found, the command must display the following information about the user:
-> Full name
-> Date Joined
-> Status
- If the user is not found, the command must not display any output.
- The command must be efficient. It should not take a long time to search the system for a user or to display the user's details.
- The command must exclude sensitive information about the user like their email id, phone number, etc.

**Comment by iamitprakash** [comment]
compiled set of information excluding PII info like email address, phone # what nit...
