### ISSUE TITLE
feat: API endpoint for removing a role from the discord server

### ISSUE THREAD

**Issue by VaibhavSingh8** [Real-Dev-Squad/discord-slash-commands#272]
### Issue Description

Implement functionality to delete a guild role from a Discord server using the Discord API. Currently, our application cannot programmatically remove roles from a server, which is necessary for role management and server organization.

### Expected Behavior

When a DELETE request is sent to the Discord API endpoint for role deletion (DELETE /guilds/{guild.id}/roles/{role.id}), the specified role should be completely removed from the Discord server. This includes:

1. The role being deleted from the server's role list
2. The role being automatically removed from all members who previously had it
3. The API returning a successful response code (204 No Content) upon completion
4. Any references to the deleted role in channel permissions being cleared

The implementation should handle authentication using a bot token with the "Manage Roles" permission, properly format the API request, and provide appropriate error handling for cases such as invalid role IDs or insufficient permissions.

### Current Behavior

Currently, there is no functionality implemented to remove a guild role from the Discord server using the API. The application does not have the capability to programmatically delete roles, which limits our ability to manage server roles effectively.

### Screenshots

N/A

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Attempt to use the application to delete a role from a Discord server
2. Observe that no option or functionality exists to perform this action
3. Check the codebase and confirm the absence of API calls to Discord's role deletion endpoint

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information

Note: The priority is set to High because this is a dependency for an upcoming feature on the Dashboard site.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by pankajjs** [comment]
@yesyash Can you assign this issue to me?

**Comment by yesyash** [comment]
> @yesyash Can you assign this issue to me?

Has @ankushdharkar been made aware of this issue ticket?

**Comment by pankajjs** [comment]
> > @yesyash Can you assign this issue to me?
> 
> Has @ankushdharkar been made aware of this issue ticket?

yes. He also has approved the TCR.

**Comment by yesyash** [comment]
> > > @yesyash Can you assign this issue to me?
> 
> > 
> 
> > Has @ankushdharkar been made aware of this issue ticket?
> 
> 
> 
> yes. He also has approved the TCR.

Assigned the issue ticket to you
