### ISSUE TITLE
[TEST]: Steps to remove a env var to test for the scenario when one of the env var is not present. 

### ISSUE THREAD

**Issue by Saitharun279** [Real-Dev-Squad/discord-slash-commands#288]
### Steps to remove a env var to test for the scenario when one of the env var is not present
There are two ways to test this scenario:
1. Remove one of the existing env vars from the Github Actions secrets. 
2. Add one temporary env var whose value is not present in the Github Actions secrets or it is not injected as env var in the Github Actions job. 

The suitable env vars to be removed are `DISCORD_APPLICATION_ID` or `CLOUDFLARE_ACCOUNT_ID`, because they can be obtained back from discord or cloudfare accounts. 

Steps to remove `CLOUDFLARE_ACCOUNT_ID` from Github Actions secrets:

1. Delete the existing `CLOUDFLARE_ACCOUNT_ID` from Github Actions secrets. 
<img width="1601" alt="Screenshot 2024-11-09 at 2 00 00 AM" src="https://github.com/user-attachments/assets/f47e9501-f646-42a6-a02e-0ab977dce942">

2. Run the `Register and deploy Slash Commands` Github Actions again. 

3. It should fail while checking for env vars stating that `CLOUDFLARE_ACCOUNT_ID` is not set. 
<img width="1772" alt="Screenshot 2024-11-09 at 2 03 12 AM" src="https://github.com/user-attachments/assets/d43f36fc-aff1-46f3-8a55-8bf07dd78440">

4. Get the `CLOUDFLARE_ACCOUNT_ID` back by logging into cloudfare > worker & pages > overview > the cloudfare account Id will be present on the right side as shown in the below image. (Account ID is striked out in black for privacy reason. )
![image (11)](https://github.com/user-attachments/assets/b23a069f-6ef6-48a8-a317-e0cdd642dfbf)

5. Add the `CLOUDFLARE_ACCOUNT_ID` back as a Github Actions secrets. 
<img width="1671" alt="Screenshot 2024-11-09 at 2 04 38 AM" src="https://github.com/user-attachments/assets/e67e8312-8dce-453b-8576-c8b5889f60c8">

6. Re run the failed Github Actions job, this time it should finish the workflow successfully and deploy it to cloudfare. 
<img width="1746" alt="Screenshot 2024-11-09 at 2 06 03 AM" src="https://github.com/user-attachments/assets/748e58d2-283a-4c37-a6ad-ffcb8708bce4">

**Comment by prakashchoudhary07** [comment]
## Deleted  Cloudflare account ID

<img width="893" alt="image" src="https://github.com/user-attachments/assets/46c783d2-548e-4372-b094-dbfb4e6d19c0">

**Comment by prakashchoudhary07** [comment]
Build did not succeed after deleting the Cloudflare account id

<img width="560" alt="image" src="https://github.com/user-attachments/assets/ba538b41-1830-4b31-9f46-61178de68eed">

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/8481750f-40cc-400a-9c74-8dc0e565c6b0">

**Comment by prakashchoudhary07** [comment]
Added Cloudflare account Id, back
<img width="965" alt="image" src="https://github.com/user-attachments/assets/a086d25d-6d9e-459b-8ca9-a115f8721176">

**Comment by prakashchoudhary07** [comment]
Build succesful

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/163045a8-1d77-47be-913b-ae4c393650e1">

**Comment by iamitprakash** [comment]
CC- @prakashchoudhary07

**Comment by Saitharun279** [comment]
After deleting env var in production, the Github Action failed. 
![image-1](https://github.com/user-attachments/assets/52e917b8-cc91-4cc1-a324-63b3f7e2896d)

Error message in logs:
![image-3](https://github.com/user-attachments/assets/d17089b2-4188-4dac-ac67-209aa19c1738)

After re adding it back, Github Action finished successfully. 
![image-2](https://github.com/user-attachments/assets/1643bc80-abdf-4682-9b9c-ffcd167c2688)

**Comment by Saitharun279** [comment]
Testing is finished in both staging and production.
