### ISSUE TITLE
Create API endpoint for retrieving Discord role IDs

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/discord-slash-commands#79]
# Issue Title: Create API endpoint for retrieving Discord role IDs

## Description:
As developers at the Real Dev Squad, we would greatly benefit from having an API endpoint that enables us to retrieve role IDs for our Discord server. This functionality will empower us to manage and leverage role-related information within our applications efficiently.

## Requirements:
1. Develop an API endpoint that allows us to fetch all role IDs from our Real Dev Squad server on Discord.
2. Implement a method within the API to retrieve a specific role ID by its name from our Real Dev Squad server on Discord.

## Additional Information:
The API should be meticulously designed to integrate seamlessly with the Discord API, utilizing the appropriate authentication mechanisms to access server information. Adhering to RESTful principles, the API should return the retrieved role ID(s) in a standardized format, such as JSON.

## Acceptance Criteria:
- The API endpoint should successfully retrieve all role IDs from our Real Dev Squad server.
- The API endpoint should accurately retrieve a role ID by its name from our Real Dev Squad server.
- The API should gracefully handle errors and provide clear, informative error responses for scenarios like invalid server or role names.
- Comprehensive documentation must accompany the API, providing detailed instructions for authentication and examples showcasing API usage.
- Write good test cases by mocking the responses and ensuring 100% test coverage.

## Follow-Up Ticket
- https://github.com/Real-Dev-Squad/website-backend/issues/1195

## Note:
This issue is a crucial step toward developing an API endpoint that seamlessly integrates with the Discord API, handles authentication, implements robust error handling, and ultimately enhances our ability to manage and leverage role-related information within our applications at the Real Dev Squad.

**Comment by bksh05** [comment]
Hi @RitikJaiswal75, 
I want to work on this feature. 

I am going to set everything up and go through the code once. I will get back with ETA soon.

**Comment by bksh05** [comment]
Hey @RitikJaiswal75, 
I went through the code and discord API documentation. 
And I believe, I will be able to complete this task (i.e get it merged to staging) by 2nd July EOD 
Let me know if you need a detailed breakup of the timeline.
