### ISSUE TITLE
Add description to the message after using /verify

### ISSUE THREAD

**Issue by kotesh-arya** [Real-Dev-Squad/discord-slash-commands#85]
## Description
after using `/verify ` command, the reply message is showing just a link.

![InkedDiscord-verification-RDS_LI](https://github.com/Real-Dev-Squad/discord-slash-commands/assets/69259490/944dd951-8acb-4687-be11-1c365155acd9)

 It will be very helpful if a bit of description is added to it, something like: **_click this link for further steps_**

**Comment by shreya-mishra** [comment]
assigned @kotesh-arya
